CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y

CONFIG_LOG=y
#backend uart ha era- detara kesu
CONFIG_LOG_BACKEND_UART=y
CONFIG_ZMK_LOG_LEVEL_DBG=y
CONFIG_LOG_BUFFER_SIZE=4096
#RAM ni Yoyuu ga arunara
#CONFIG_LOG_BUFFER_SIZE=8192